# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/mainwindowkn5530.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BaseMainWindow(QtWidgets.QMainWindow):
    def setupUi(self, BaseMainWindow):
        BaseMainWindow.setObjectName("BaseMainWindow")
        BaseMainWindow.setWindowModality(QtCore.Qt.NonModal)
        BaseMainWindow.resize(303, 759)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("diamond.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BaseMainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(BaseMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(0, 670, 301, 61))
        self.submitButton.setAcceptDrops(False)
        self.submitButton.setObjectName("submitButton")
        self.oldGuessesTable = QtWidgets.QTableWidget(self.centralwidget)
        self.oldGuessesTable.setEnabled(False)
        self.oldGuessesTable.setGeometry(QtCore.QRect(10, 10, 201, 501))
        self.oldGuessesTable.setMaximumSize(QtCore.QSize(16777215, 16777213))
        self.oldGuessesTable.setBaseSize(QtCore.QSize(4, 10))
        self.oldGuessesTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.oldGuessesTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.oldGuessesTable.setAutoScroll(False)
        self.oldGuessesTable.setWordWrap(False)
        self.oldGuessesTable.setCornerButtonEnabled(False)
        self.oldGuessesTable.setObjectName("oldGuessesTable")
        self.oldGuessesTable.setColumnCount(4)
        self.oldGuessesTable.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.oldGuessesTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.oldGuessesTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.oldGuessesTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.oldGuessesTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.oldGuessesTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.oldGuessesTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.oldGuessesTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.oldGuessesTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.oldGuessesTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.oldGuessesTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.oldGuessesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.oldGuessesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.oldGuessesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.oldGuessesTable.setHorizontalHeaderItem(3, item)
        self.oldGuessesTable.horizontalHeader().setVisible(False)
        self.oldGuessesTable.horizontalHeader().setDefaultSectionSize(50)
        self.oldGuessesTable.horizontalHeader().setMinimumSectionSize(0)
        self.oldGuessesTable.verticalHeader().setVisible(False)
        self.oldGuessesTable.verticalHeader().setCascadingSectionResizes(False)
        self.oldGuessesTable.verticalHeader().setDefaultSectionSize(50)
        self.oldGuessesTable.verticalHeader().setMinimumSectionSize(0)
        self.colorsTable = QtWidgets.QTableWidget(self.centralwidget)
        self.colorsTable.setGeometry(QtCore.QRect(0, 600, 301, 51))
        self.colorsTable.setStyleSheet("border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.colorsTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.colorsTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.colorsTable.setRowCount(1)
        self.colorsTable.setColumnCount(6)
        self.colorsTable.setObjectName("colorsTable")
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.colorsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.colorsTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.colorsTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.colorsTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.colorsTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.colorsTable.setItem(0, 5, item)
        self.colorsTable.horizontalHeader().setVisible(False)
        self.colorsTable.horizontalHeader().setDefaultSectionSize(50)
        self.colorsTable.verticalHeader().setVisible(False)
        self.colorsTable.verticalHeader().setDefaultSectionSize(50)
        self.thisGuessTable = QtWidgets.QTableWidget(self.centralwidget)
        self.thisGuessTable.setGeometry(QtCore.QRect(10, 530, 201, 51))
        self.thisGuessTable.setAcceptDrops(True)
        self.thisGuessTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.thisGuessTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.thisGuessTable.setRowCount(1)
        self.thisGuessTable.setColumnCount(4)
        self.thisGuessTable.setObjectName("thisGuessTable")
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.thisGuessTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.thisGuessTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.thisGuessTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.thisGuessTable.setItem(0, 3, item)
        self.thisGuessTable.horizontalHeader().setVisible(False)
        self.thisGuessTable.horizontalHeader().setDefaultSectionSize(50)
        self.thisGuessTable.verticalHeader().setVisible(False)
        self.thisGuessTable.verticalHeader().setDefaultSectionSize(50)
        self.scoreTable = QtWidgets.QTableWidget(self.centralwidget)
        self.scoreTable.setEnabled(False)
        self.scoreTable.setGeometry(QtCore.QRect(230, 10, 61, 501))
        self.scoreTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scoreTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scoreTable.setShowGrid(True)
        self.scoreTable.setWordWrap(False)
        self.scoreTable.setCornerButtonEnabled(False)
        self.scoreTable.setRowCount(10)
        self.scoreTable.setColumnCount(4)
        self.scoreTable.setObjectName("scoreTable")
        self.scoreTable.horizontalHeader().setVisible(False)
        self.scoreTable.horizontalHeader().setDefaultSectionSize(15)
        self.scoreTable.verticalHeader().setVisible(False)
        self.scoreTable.verticalHeader().setDefaultSectionSize(50)
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(230, 530, 61, 51))
        self.resetButton.setObjectName("resetButton")
        BaseMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(BaseMainWindow)
        self.statusbar.setObjectName("statusbar")
        BaseMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(BaseMainWindow)
        self.colorsTable.cellChanged['int','int'].connect(BaseMainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(BaseMainWindow)

    def retranslateUi(self, BaseMainWindow):
        _translate = QtCore.QCoreApplication.translate
        BaseMainWindow.setWindowTitle(_translate("BaseMainWindow", "Mastermind"))
        self.submitButton.setText(_translate("BaseMainWindow", "Submit"))
        item = self.oldGuessesTable.verticalHeaderItem(0)
        item.setText(_translate("BaseMainWindow", "New Row"))
        item = self.oldGuessesTable.verticalHeaderItem(1)
        item.setText(_translate("BaseMainWindow", "New Row"))
        item = self.oldGuessesTable.verticalHeaderItem(2)
        item.setText(_translate("BaseMainWindow", "New Row"))
        item = self.oldGuessesTable.verticalHeaderItem(3)
        item.setText(_translate("BaseMainWindow", "New Row"))
        item = self.oldGuessesTable.verticalHeaderItem(4)
        item.setText(_translate("BaseMainWindow", "New Row"))
        item = self.oldGuessesTable.verticalHeaderItem(5)
        item.setText(_translate("BaseMainWindow", "New Row"))
        item = self.oldGuessesTable.verticalHeaderItem(6)
        item.setText(_translate("BaseMainWindow", "New Row"))
        item = self.oldGuessesTable.verticalHeaderItem(7)
        item.setText(_translate("BaseMainWindow", "New Row"))
        item = self.oldGuessesTable.verticalHeaderItem(8)
        item.setText(_translate("BaseMainWindow", "New Row"))
        item = self.oldGuessesTable.verticalHeaderItem(9)
        item.setText(_translate("BaseMainWindow", "New Row"))
        __sortingEnabled = self.colorsTable.isSortingEnabled()
        self.colorsTable.setSortingEnabled(False)
        self.colorsTable.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.thisGuessTable.isSortingEnabled()
        self.thisGuessTable.setSortingEnabled(False)
        self.thisGuessTable.setSortingEnabled(__sortingEnabled)
        self.resetButton.setText(_translate("BaseMainWindow", "Reset"))

